name: 'AWS SAM'

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  aws-sam:
    name: 'AWS SAM'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          role-duration-seconds: 900

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get Yarn Cache Directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Setup Cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Yarn Install
        run: yarn --prefer-offline

      - name: Test
        run: yarn test

      - name: Build
        env:
          NODE_ENV: production
        run: yarn build

      - name: Deploy - Dev
        if: github.ref == 'refs/heads/main'
        run: yarn deploy --config-env dev

      - name: Deploy - Prod
        if: startsWith(github.ref, 'refs/tags/')
        run: yarn deploy --config-env prod
